name: CI/CD Pipeline

# Gatilho: O workflow será executado em cada push para a branch "main"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Permissões mínimas para o job
permissions:
  contents: read

jobs:
  # O nome do job é "lint-and-test"
  lint-and-test:
    # O job será executado em uma máquina virtual Ubuntu
    runs-on: ubuntu-latest
    strategy:
      # Executar para múltiplas versões do Python para garantir a compatibilidade
      matrix:
        python-version: ["3.10"]

    steps:
      # 1. Clona o repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura a versão do Python especificada na matriz
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # Habilita o cache de dependências para acelerar execuções futuras
          cache: 'pip'

      # 3. Instala as dependências a partir do arquivo requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      # 4. Executa o linter (pylint) para análise estática do código
      - name: Analyse code with pylint
        run: |
          python -m pylint $(git ls-files '*.py')

      # Etapa futura sugerida: Adicionar testes com pytest
      # - name: Run tests with pytest
      #   run: |
      #     pip install pytest
      #     pytest

  deploy:
    deploy:
    name: Deploy project
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: 'actions/checkout@v2'
        with:
          ref: main
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          environment: production
      - name: Set up SSH Key and Deploy my App on Server
        # run: |
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            git config --global url."https://${{ secrets.PERSONAL_GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"
            cd /root/python
            git pull origin main
            python3 -m venv venv
            source venv/bin/activate

            pip install -r requirements.txt

      - name: Update deployment Status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
